version: "3.6"

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=rhribeiro25
      - RABBITMQ_DEFAULT_PASS=alura

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#    command: >
#      bash -c
#      "(--topic created-promotion-to-product-topic &) && (supervisord -n)"

  postgres-payments:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=rhribeiro25
      - POSTGRES_PASSWORD=alura
      - POSTGRES_DB=alurafood-payments
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./data/postgres-payments:/var/lib/postgresql/data

  postgres-orders:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=rhribeiro25
      - POSTGRES_PASSWORD=alura
      - POSTGRES_DB=alurafood-orders
    ports:
      - "6432:5432"
    expose:
      - 6432
    volumes:
      - ./data/postgres-orders:/var/lib/postgresql/data

  postgres-promotions:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=rhribeiro25
      - POSTGRES_PASSWORD=alura
      - POSTGRES_DB=alurafood-promotions
    ports:
      - "7432:5432"
    expose:
      - 7432
    volumes:
      - ./data/postgres-promotions:/var/lib/postgresql/data

  postgres-evaluations:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=rhribeiro25
      - POSTGRES_PASSWORD=alura
      - POSTGRES_DB=alurafood-evaluations
    ports:
      - "8432:5432"
    expose:
      - 8432
    volumes:
      - ./data/postgres-evaluations:/var/lib/postgresql/data

volumes:
  rabbitmq:
  kafka:
  postgres-payments:
  postgres-orders:
  postgres-promotions:
  postgres-evaluations:
